### ISSUE TITLE
Option "Only Self Assigned" shows only tasks assigned ONLY to me

### ISSUE THREAD

**Issue by dimitrisscript** [Teamwork/vscode-projects#2] opened 2019-08-20 09:11 UTC
Using the option "Only Self Assigned (only show tasks assigned to you)" doesn't work as expected (at least it's not consistent with teamwork.com)

![Code_9UuN0XYsWa](https://user-images.githubusercontent.com/7396778/63334077-42a75b00-c343-11e9-990d-36b7118565a7.png)

It shows only tasks that are assigned ONLY to 1 person: you. 

Which means that if a task is assigned to 2 people (including you), the extension will not show this task. In my current company, many tasks are assigned to 2-3 people, so it's not very useful...

Can we have this option showing all tasks the user is assigned to?

**Comment by DeeJayTC** [comment] 2019-08-29 15:14
Hey @dimitrisscript I just had a look and as far as i can see its working fine for tasks assigned to multiple people:
![image](https://user-images.githubusercontent.com/4077759/63952705-527c1900-ca80-11e9-9150-111b98717f4f.png)

This is with
* Only Self Assigned -> True
* Show Anyone -> False

Can you check again if this is still an issue for you?

**Comment by dimitrisscript** [comment] 2019-08-30 11:24
Then the error must be elsewhere: I think the extension doesn't show subtasks.

I can see 1 parent task and a lot of subtasks assigned to me when I use teamwork.com
When using the extension, I can only see the parent task but none of the subtasks.

**Comment by DeeJayTC** [comment] 2019-08-30 13:34
ahh thats a good hint, let me see what i can find out here. 

Think someone mentioned that earlier and we could not reproduce it properly.

**Comment by DeeJayTC** [comment] 2019-09-10 11:22
@dimitrisscript Hey,
i'm afraid i'm unable to reproduce your issue here. Could you please send a mail to support@teamwork.com and we can follow up from there? Might need to use try it with your installation to see whats different to my test environment.

**Closed as completed by DeeJayTC** 2019-09-10 11:22 UTC
